### ISSUE TITLE
wat

### ISSUE THREAD

**Issue by cb130felix** [arthurflor/SearchDetran#1]
Tipo, vai ser essa parada mesmo o projeto de SD? Pq eu acho perda de tempo fazer o aplicativo que consulta as paradas no site do detran dnv. O que eu tinha feito em C e tal.

**Comment by arthurflor** [comment]
já fiz ._.

**Comment by arthurflor** [comment]
mãos à obra, homem

**Comment by cb130felix** [comment]
Eita carai
